#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo
#    username: root
#    password: ljh/1989
#  jpa:
#    show_sql: true
#    generate_ddl: true
#    hibernate:
#      ddl_auto: update